"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['main.py']
DATA_FILES = ["device_info.py", "info.py", "info_report.py", "info_task.py",
              "task.py", "utils.py"]
OPTIONS = {"includes": ["jinja2", "subprocess"]}
setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
